version: "3.9"

services:
  cs2_redis:
    image: redis:7
    container_name: cs2_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # cs2_celery_worker:
  #   build:
  #     context: .
  #     dockerfile: worker/Dockerfile
  #   container_name: celery_worker
  #   env_file:
  #     - .env
  #   depends_on:
  #     cs2_redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./data:/app/data

  # cs2_fastapi:
  #   build:
  #     context: .
  #     dockerfile: forecaster/Dockerfile  # Your FastAPI Dockerfile path
  #   container_name: fastapi_app
  #   env_file:
  #     - .env
  #   depends_on:
  #     cs2_redis:
  #       condition: service_healthy
  #   ports:
  #     - "8000:8000"
    
