version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file: example.env

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file: example.env

  telegram-bot:
    build: .
    command: python -m app.bot
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: example.env

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
