version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cs2_db
      POSTGRES_USER: cs2_user
      POSTGRES_PASSWORD: cs2_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: >
      redis-server --requirepass redis_password --databases 1
    ports:
      - "6379:6379"

volumes:
  postgres_data:
