version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.10
    container_name: clickhouse
    hostname: clickhouse
    env_file:
      - .env
    ports:
      - "${CLICKHOUSE_PORT}:9000"      
      - "${CLICKHOUSE_HTTP_PORT}:8123" 
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8123/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"         
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  clickhouse_data:
