[tool.poetry]
name = "bil-cs2"
version = "0.1.0"
description = "cs2 ml service"
authors = [""]
package-mode = false
exclude = [".venv"]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
yoyo-migrations = "^9.0.0"
psycopg2-binary = "^2.9.11"
numpy = "^2.3.3"
scikit-learn = "^1.7.2"
clickhouse-driver = "^0.2.9"
dateutils = "^0.6.12"
pika = "^1.3.2"
pydantic-settings = "^2.11.0"
tqdm = "^4.67.1"
python-dotenv = "^1.1.1"
pandas = "^2.3.3"
torch = "^2.9.0"
django = "^5.2.7"
django-celery-beat = "^2.8.1"
celery = "^5.5.3"
redis = "^6.4.0"
optuna = "^4.5.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.0"
black = "^25.9.0"
isort = "^5.13.2"
autoflake = "^2.3.1"
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# --- Ruff configuration ---
[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [".venv", "venv", "__pycache__", "data"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

# --- isort configuration ---
[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
multi_line_output = 3
skip = [".venv", "data"]

# --- Black configuration ---
[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(\.venv|venv|__pycache__|data)/
'''

# --- Pytest configuration ---
[tool.pytest.ini_options]
addopts = "-v --disable-warnings"
testpaths = ["tests"]
pythonpath = "."
