[tool.poetry]
name = "bil-cs2"
version = "0.1.0"
description = "cs2 ml service"
authors = [""]
package-mode = false
exclude = [".venv"]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
clickhouse-driver = "^0.2.9"
python-dotenv = "^1.1.1"
python-dateutil = "^2.9.0"
pandas = "^2.3.3"
pydantic = "^2.12.0"
numpy = "^2.3.3"
scikit-learn = "^1.7.2"
tqdm = "^4.67.1"
django = "^5.2.7"
django-celery-beat = "^2.8.1"
psycopg2-binary = "^2.9.9"
redis = "^6.4.0"
pytest = "^8.4.2"
testcontainers = "^4.13.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.0"
isort = "^5.13.2"
autoflake = "^2.3.0"
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# --- Ruff configuration ---
[tool.ruff]
line-length = 88
target-version = "py311"
exclude = ["venv", ".venv", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

# --- isort configuration ---
[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
multi_line_output = 3

# --- Pytest configuration ---
[tool.pytest.ini_options]
addopts = "-v --disable-warnings"
testpaths = ["tests"]
pythonpath = "."
