[tool.poetry]
name = "prediction-service"
version = "0.1.0"
description = "Сервис для ML предсказаний"
authors = ["Your Name <you@example.com>"]
package-mode = false  # отключаем установку текущего проекта

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
psycopg2-binary = "*"
scikit-learn = "*"
scipy = "*"
numpy = "*"
python-dateutil = "*"
joblib = "*"
python-dotenv = "*"
redis = "*"
celery = "*"

django = "*"
djangorestframework = "*"
djangorestframework-simplejwt = "*"

pytest = "*"
pytest-asyncio = "*"
testcontainers = "*"
httpx = "*"
aiogram = "^3.22.0"
drf-spectacular = "^0.29.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-django = "*"
autoflake = "*"
isort = "*"
ruff = "*"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "*_test.py"]
addopts = "-v --disable-warnings -p no:cacheprovider --log-cli-level=INFO"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
