# Generated by Django 5.2.7 on 2025-10-21 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("map_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Map",
                "verbose_name_plural": "Maps",
            },
        ),
        migrations.CreateModel(
            name="MLPipeline",
            fields=[
                ("ml_pipeline_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "pipeline_path",
                    models.FilePathField(
                        match=".*\\.pkl$", path="data/ml/", recursive=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ML Pipeline",
                "verbose_name_plural": "ML Pipelines",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="MLMetrics",
            fields=[
                ("ml_metrics_id", models.AutoField(primary_key=True, serialize=False)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("loss", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.mlpipeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Metric",
                "verbose_name_plural": "ML Metrics",
            },
        ),
    ]
