# Generated by Django 5.2.7 on 2025-10-26 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "map_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "map",
            },
        ),
        migrations.CreateModel(
            name="MLPipeline",
            fields=[
                (
                    "pipeline_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path_to_pipeline_file", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ml_pipeline",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "player_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "player",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "team_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="MLPipelineMetrics",
            fields=[
                (
                    "metrics_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path_to_metrics_file", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.mlpipeline",
                    ),
                ),
            ],
            options={
                "db_table": "ml_pipeline_metrics",
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "prediction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team1_win_probability", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В ожидании"),
                            ("IN_PROGRESS", "В процессе"),
                            ("COMPLETED", "Завершено"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="predictions",
                        to="app.map",
                    ),
                ),
                (
                    "ml_pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.mlpipeline",
                    ),
                ),
                (
                    "team1_players",
                    models.ManyToManyField(
                        related_name="team1_predictions", to="app.player"
                    ),
                ),
                (
                    "team2_players",
                    models.ManyToManyField(
                        related_name="team2_predictions", to="app.player"
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team1_predictions",
                        to="app.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team2_predictions",
                        to="app.team",
                    ),
                ),
                (
                    "team_id_start_ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="start_ct_predictions",
                        to="app.team",
                    ),
                ),
            ],
            options={
                "db_table": "prediction",
            },
        ),
    ]
