# fluentd/conf/fluent.conf

# Input: HTTP, принимаем JSON логи
<source>
  @type http
  port 9880                # Порт для приёма HTTP POST
  bind 0.0.0.0
  body_size_limit 32m
  <parse>
    @type json
  </parse>
</source>

# Match all logs и сохраняем в файл
<match **>
  @type file
  path /fluentd/log/django_logs.log   # Путь внутри контейнера
  append true
  format json
  time_slice_format %Y%m%d
  time_slice_wait 10m
  compress gzip
</match>

# Для вывода в stdout (по желанию, для отладки)
<match debug.**>
  @type stdout
</match>
