name: CI

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
  pull_request:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run lint
        run: make lint

      - name: Prepare environment for Docker tests
        run: cp auth/example.env auth/.env

      - name: Run tests in Docker
        run: make docker-test
